---
abstract: 'emit POE events for Gtk2 callbacks'
author:
  - 'Martijn van Beers  <martijn@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: POE-Session-GladeXML2
no_index:
  directory:
    - inc
    - t
provides:
  POE::Session::GladeXML2:
    file: lib/POE/Session/GladeXML2.pm
    version: 0.40
requires:
  Carp: 1.08
  Gtk2::GladeXML: 1.006
  POE: 1.0002
  POE::Loop::Glib: 0.0034
  perl: 5.6.0
version: 0.40
