# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Session-GladeXML2
version:      0.3.1
version_from: lib/POE/Session/GladeXML2.pm
installdirs:  site
requires:
    Gtk2::GladeXML:                0
    POE:                           0.31
    POE::Loop::Glib:               0.0022

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
